### ISSUE TITLE
Thanks and minor suggestion

### ISSUE THREAD

**Issue by DannyBen** [bogdanvlviv/minitest-mock_expectations#1]
Hey, this is a great life saving gem. It brings the nice RSpec expectations easily and intuitively into my Rails projects, so thanks for that.

One thing I noticed - it is hard to find this gem. Searching "minitest mock expectations" does not show this repo anywhere in the first pages, and I don't remember even how I did find it - perhaps changing the README H1 to "Minitest Mock Expectations" will help Google?

**Comment by bogdanvlviv** [comment]
@DannyBen Thanks you for the suggestion. I just changed the h1 in https://github.com/bogdanvlviv/minitest-mock_expectations/commit/83f97c241e268b4883f002971b47b1a986f8d5ca.

Actually, I expect that merging https://github.com/seattlerb/minitest/pull/781 will help to find this gem as well.
